In [11]:
import os
import regex as re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### CPI

In [ ]:
cpi = pd.read_excel('/content/drive/MyDrive/Leipzig/Divergenz_Projekt/Monthly_Index.xlsx')

In [ ]:
cpi

,GEOGRAPHICAL AREA,Austria (AT),Belgium (BE),Cyprus (CY),Estonia (EE),Germany (DE),Spain (ES),Finland (FI),France (FR),Greece (GR),...,Italy (IT),Lithuania (LT),Luxembourg (LU),Latvia (LV),Malta (MT),Netherlands (NL),Portugal (PT),Slovenia (SI),Slovakia (SK),Inflation Standard Dev
0,1999-01-31,73.27,72.44,NaN,NaN,77.2,67.98,73.50,76.16,NaN,...,71.6,NaN,66.16,NaN,NaN,71.66,70.44,NaN,NaN,3.578668
1,1999-02-28,73.42,72.59,NaN,NaN,77.3,68.04,73.79,76.43,NaN,...,71.8,NaN,67.41,NaN,NaN,72.14,70.44,NaN,NaN,3.459843
2,1999-03-31,73.49,72.66,NaN,NaN,77.5,68.30,73.93,76.69,NaN,...,71.9,NaN,67.48,NaN,NaN,72.90,70.71,NaN,NaN,3.480586
3,1999-04-30,73.49,72.94,NaN,NaN,77.8,68.56,74.57,76.92,NaN,...,72.0,NaN,67.81,NaN,NaN,73.11,71.18,NaN,NaN,3.503903
4,1999-05-31,73.56,73.08,NaN,NaN,77.8,68.56,74.79,76.91,NaN,...,72.2,NaN,68.00,NaN,NaN,73.11,71.25,NaN,NaN,3.432890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,2023-10-31,132.24,127.15,117.32,150.45,127.2,121.69,118.93,121.61,118.17,...,122.2,150.68,124.12,142.93,121.96,129.56,120.65,128.05,139.89,10.422723
298,2023-11-30,132.46,127.05,115.51,150.48,126.3,121.05,118.34,121.32,116.86,...,121.5,150.07,123.36,142.81,118.48,127.63,119.39,126.99,140.14,10.823260
299,2023-12-31,133.08,128.45,114.09,150.45,126.6,121.06,118.61,121.49,116.97,...,121.7,149.17,122.85,141.77,118.30,127.88,118.56,126.29,139.96,10.737561
300,2024-01-31,132.60,127.51,112.67,152.35,126.4,120.82,119.01,121.20,115.89,...,120.4,149.34,122.31,142.87,117.77,128.08,118.36,125.57,141.02,11.387758
301,2024-02-29,133.47,130.54,113.60,152.54,127.2,121.29,119.80,122.35,116.04,...,120.4,150.38,124.34,142.99,118.06,129.29,118.54,126.34,141.82,11.367306

In [ ]:
cpi.index = pd.to_datetime(cpi['GEOGRAPHICAL AREA'], format='%Y-%m-%d')
cpi = cpi.drop('GEOGRAPHICAL AREA', axis=1)

In [ ]:
cpi_q = cpi.resample('QS').mean()

In [ ]:
cpi_q

,Austria (AT),Belgium (BE),Cyprus (CY),Estonia (EE),Germany (DE),Spain (ES),Finland (FI),France (FR),Greece (GR),Croatia (HR),...,Italy (IT),Lithuania (LT),Luxembourg (LU),Latvia (LV),Malta (MT),Netherlands (NL),Portugal (PT),Slovenia (SI),Slovakia (SK),Inflation Standard Dev
GEOGRAPHICAL AREA,,,,,,,,,,,,,,,,,,,,,
1999-01-01,73.393333,72.563333,NaN,NaN,77.333333,68.106667,73.740000,76.426667,NaN,65.660000,...,71.766667,NaN,67.016667,NaN,NaN,72.233333,70.530000,NaN,NaN,3.506366
1999-04-01,73.440000,72.986667,NaN,NaN,77.800000,68.560000,74.716667,76.913333,NaN,66.243333,...,72.133333,NaN,67.916667,NaN,NaN,72.993333,71.270000,NaN,NaN,3.455755
1999-07-01,73.420000,73.056667,NaN,NaN,78.133333,69.146667,74.743333,76.816667,NaN,66.713333,...,72.466667,NaN,67.870000,NaN,NaN,72.783333,71.270000,NaN,NaN,3.381522
1999-10-01,74.063333,73.406667,NaN,NaN,78.066667,69.453333,75.150000,77.180000,NaN,66.850000,...,72.933333,NaN,68.660000,NaN,NaN,73.220000,71.666667,NaN,NaN,3.332641
2000-01-01,74.683333,73.763333,NaN,NaN,78.566667,70.123333,75.773333,77.626667,NaN,67.793333,...,73.466667,NaN,69.050000,NaN,NaN,73.380000,71.690000,NaN,NaN,3.309209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-01,128.046667,125.960000,111.400,146.166667,123.833333,117.866667,118.376667,118.510000,113.026667,122.916667,...,119.666667,148.726667,119.966667,142.250000,114.776667,125.430000,116.516667,122.186667,136.650000,11.076449
2023-04-01,130.120000,124.783333,114.050,150.473333,125.833333,119.726667,119.050000,120.573333,116.316667,126.316667,...,121.600000,149.830000,121.526667,144.550000,121.653333,128.120000,119.603333,125.273333,139.206667,11.006446
2023-07-01,130.836667,125.993333,116.910,150.993333,127.100000,120.696667,118.633333,121.423333,116.663333,129.503333,...,120.700000,149.550000,123.140000,144.223333,124.033333,129.320000,120.250000,126.943333,139.286667,10.670209
2023-10-01,132.593333,127.550000,115.640,150.460000,126.700000,121.266667,118.626667,121.473333,117.333333,129.010000,...,121.800000,149.973333,123.443333,142.503333,119.580000,128.356667,119.533333,127.110000,139.996667,10.661182
2024-01-01,133.035000,129.025000,113.135,152.445000,126.800000,121.055000,119.405000,121.775000,115.965000,128.380000,...,120.400000,149.860000,123.325000,142.930000,117.915000,128.685000,118.450000,125.955000,141.420000,11.377532

In [ ]:
cpi_q.to_excel('/content/drive/MyDrive/Leipzig/Divergenz_Projekt/Monthly_Index_Q.xlsx')

### Wages

In [ ]:
wages = pd.read_excel('/content/drive/MyDrive/Leipzig/Divergenz_Projekt/Wages_Q.xlsx')

In [ ]:
wages.index = pd.to_datetime(wages['GEOGRAPHICAL AREA'], format='%Y-%m-%d')
wages = wages.drop('GEOGRAPHICAL AREA', axis=1)

In [ ]:
wages_percentage = wages.pct_change(4) * 100

In [ ]:
wages_percentage.to_excel('/content/drive/MyDrive/Leipzig/Divergenz_Projekt/Wages_Percentage_Q.xlsx')

### Balance of Trade

In [ ]:
bot = pd.read_excel('/content/drive/MyDrive/Leipzig/Divergenz_Projekt/transformed_net_exports_per_month.xlsx')

In [ ]:
bot.index = pd.to_datetime(bot['Date'], format='%Y-%m-%d')
bot = bot.drop('Date', axis=1)

In [ ]:
bot = bot.resample('QS').mean()

In [ ]:
bot.to_excel('/content/drive/MyDrive/Leipzig/Divergenz_Projekt/Balance_of_Trade_Q.xlsx')

### Shadow Rate

In [16]:
srate = pd.read_excel('/content/drive/MyDrive/Leipzig/Divergenz_Projekt/shadowrate_ECB.xls', names=['Date', 'Rate'] )

In [19]:
srate['Date'] = pd.to_datetime(srate['Date'], format='%Y%m')
srate.set_index('Date', inplace=True)

In [20]:
srate_quarterly = srate.resample('Q').mean()

In [22]:
srate_quarterly.to_excel('/content/drive/MyDrive/Leipzig/Divergenz_Projekt/Srate_Q.xlsx')